const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

const keyManager = require('./keyManager');
const earningsTracker = require('./earningsTracker');
const telegramNotifier = require('./telegramNotifier');

// ─────────────────────────────────────────────────────────────────────────────
// CONFIG — 9Router + Kiro AI (Claude Sonnet 4.5 FREE, no API key needed)
// ─────────────────────────────────────────────────────────────────────────────
const NINEROUTER_PORT = process.env.NINEROUTER_PORT || 8080;
const NINEROUTER_URL  = `http://127.0.0.1:${NINEROUTER_PORT}`;

// Model via Kiro AI (Free, unlimited, no API key required).
// Kiro is a Tier-3 FREE provider in 9Router — just connect it from the
// 9Router dashboard (no signup, no auth) and this model works immediately.
// Dashboard: http://localhost:${NINEROUTER_PORT}/dashboard → Providers → Kiro AI
const HERMES_MODEL    = 'kr/claude-sonnet-4.5';

// 9Router generates an API key from its dashboard (Dashboard → Keys).
// If requireApiKey is disabled in 9Router settings, leave this as a placeholder.
const NINEROUTER_KEY  = process.env.NINEROUTER_KEY || 'sk-9router-local';
// ─────────────────────────────────────────────────────────────────────────────

async function main() {
    console.log("=========================================");
    console.log("  HermesMoneyAgent Orchestrator");
    console.log(`  Model  : ${HERMES_MODEL}`);
    console.log(`  Router : ${NINEROUTER_URL}`);
    console.log("=========================================");

    const dataDir = path.join(__dirname, '..', '9router-data');
    const logsDir = path.join(__dirname, '..', 'logs');

    if (!fs.existsSync(logsDir)) fs.mkdirSync(logsDir, { recursive: true });

    // ── 1. Generate 9Router config (Gemini keys as fallback pool) ────────────
    console.log("[Orchestrator] Generating 9Router configuration...");
    keyManager.generate9RouterConfig(dataDir);

    // ── 2. Write Hermes cli-config.yaml using the real Hermes config format ──
    // Hermes Agent (NousResearch) reads cli-config.yaml from its home dir OR
    // from the project directory.  We point it to 9Router via OPENAI_BASE_URL.
    // The model alias 'kiro' maps to kr/claude-sonnet-4.5 through 9Router/Kiro.
    const hermesConfigPath = path.join(__dirname, '..', 'hermes-agent', 'cli-config.yaml');
    const hermesConfig = `# Auto-generated by HermesMoneyAgent orchestrator
# Model: ${HERMES_MODEL} via Kiro AI (FREE, no API key needed)
# Provider: 9Router local proxy at ${NINEROUTER_URL}

# Display
display:
  compact: true
  tool_progress: all
  streaming: true
  show_reasoning: false

# Context compression (auto-shrink long conversations)
compression:
  enabled: true
  threshold: 0.50
  target_ratio: 0.20
  protect_last_n: 20
  protect_first_n: 3

# Persistent memory
memory:
  memory_enabled: true
  user_profile_enabled: false
  memory_char_limit: 2200
  nudge_interval: 10
  flush_min_turns: 6

# Tool loop guardrails
tool_loop_guardrails:
  warnings_enabled: true
  hard_stop_enabled: false
  warn_after:
    exact_failure: 2
    same_tool_failure: 3
    idempotent_no_progress: 2

# Model alias — maps 'kiro' to the Kiro AI free Claude endpoint
model_aliases:
  kiro:
    model: "${HERMES_MODEL}"
    provider: custom
    base_url: "${NINEROUTER_URL}/v1"

# Browser tool
browser:
  inactivity_timeout: 120
`;
    fs.writeFileSync(hermesConfigPath, hermesConfig.trim());
    console.log(`[Orchestrator] Hermes config written → ${hermesConfigPath}`);
    console.log(`[Orchestrator] Model: ${HERMES_MODEL} via ${NINEROUTER_URL}/v1`);

    // ── 3. Start 9Router ─────────────────────────────────────────────────────
    console.log(`[Orchestrator] Starting 9Router on port ${NINEROUTER_PORT}...`);
    const routerEnv = Object.assign({}, process.env, {
        PORT: String(NINEROUTER_PORT),
        DATA_DIR: dataDir,
        HOSTNAME: '0.0.0.0',
        NEXT_PUBLIC_BASE_URL: NINEROUTER_URL,
    });

    const routerProcess = spawn(
        'node',
        [path.join(__dirname, '..', '9router', 'bin', 'n9router.js')],
        { env: routerEnv, stdio: 'pipe' }
    );

    routerProcess.stdout.on('data', data => {
        const msg = data.toString().trim();
        if (msg.match(/start|ready|listen|running/i)) {
            console.log(`[9Router] ${msg}`);
        }
    });
    routerProcess.stderr.on('data', data => {
        console.error(`[9Router ERR] ${data.toString().trim()}`);
    });
    routerProcess.on('error', err => {
        console.error(`[9Router] Failed to start: ${err.message}`);
    });

    // Wait for 9Router to bind port
    await new Promise(res => setTimeout(res, 5000));

    // ── 4. Verify 9Router is running ─────────────────────────────────────────
    try {
        const http = require('http');
        await new Promise((resolve, reject) => {
            http.get(`${NINEROUTER_URL}/api/health`, res => {
                if (res.statusCode === 200) {
                    console.log(`[9Router] Health check OK at ${NINEROUTER_URL}`);
                    console.log(`[9Router] Dashboard: ${NINEROUTER_URL}/dashboard`);
                    console.log(`[9Router] ⚠ Make sure Kiro AI is connected in the dashboard!`);
                }
                resolve();
            }).on('error', () => {
                console.warn(`[9Router] Health check failed — router may still be initializing`);
                resolve();
            });
        });
    } catch (_) {}

    // ── 5. Send Telegram start notification ──────────────────────────────────
    await telegramNotifier.sendAlert(
        `🚀 HermesMoneyAgent started!\n` +
        `Model: ${HERMES_MODEL} (Kiro AI — FREE)\n` +
        `Router: ${NINEROUTER_URL}`
    );

    // ── 6. Spawn Hermes Agent ────────────────────────────────────────────────
    // Pass OPENAI_BASE_URL + OPENAI_API_KEY so Hermes uses 9Router as provider.
    // HERMES_TUI=0 disables the TUI so logs stream cleanly in the orchestrator.
    console.log("\n[Orchestrator] Spawning Hermes Agent...");

    const hermesEnv = Object.assign({}, process.env, {
        HERMES_TUI: '0',
        OPENAI_BASE_URL: `${NINEROUTER_URL}/v1`,
        OPENAI_API_KEY: NINEROUTER_KEY,
    });

    const hermesProcess = spawn(
        path.join(__dirname, '..', 'hermes-agent', 'venv', 'bin', 'python'),
        [
            path.join(__dirname, '..', 'hermes-agent', 'hermes'),
            'chat',
            '--model', HERMES_MODEL,
            '--query',
            'Use discover_tasks tool to find legitimate microtask opportunities online ' +
            'and use complete_task tool to complete them. ' +
            'Do this until you earn $10 as fast as possible.',
        ],
        {
            env: hermesEnv,
            cwd: path.join(__dirname, '..', 'hermes-agent'),
            stdio: 'pipe',
        }
    );

    const actionLogStream = fs.createWriteStream(
        path.join(logsDir, 'actions.log'),
        { flags: 'a' }
    );

    hermesProcess.stdout.on('data', data => {
        const msg = data.toString();
        process.stdout.write(`[Hermes] ${msg}`);
        actionLogStream.write(msg);
    });
    hermesProcess.stderr.on('data', data => {
        const msg = data.toString();
        process.stderr.write(`[Hermes ERR] ${msg}`);
        actionLogStream.write(msg);
    });
    hermesProcess.on('error', err => {
        console.error(`[Hermes] Failed to start: ${err.message}`);
        console.error(`[Hermes] Make sure you ran: cd hermes-agent && ./scripts/install.sh`);
    });

    // ── 7. Periodic Telegram updates every 30 minutes ────────────────────────
    const updateInterval = setInterval(async () => {
        const total = await earningsTracker.getTotalEarnings();
        await telegramNotifier.checkPeriodicUpdate(total);
    }, 60_000);

    // ── 8. Graceful shutdown ──────────────────────────────────────────────────
    process.on('SIGINT', async () => {
        console.log("\n[Orchestrator] Shutting down gracefully (CTRL+C)...");
        clearInterval(updateInterval);
        if (routerProcess) routerProcess.kill('SIGTERM');
        if (hermesProcess) hermesProcess.kill('SIGTERM');
        await telegramNotifier.sendAlert("🛑 HermesMoneyAgent stopped gracefully.");
        actionLogStream.close();
        process.exit(0);
    });
}

main().catch(err => {
    console.error("[Orchestrator] Fatal Error:", err);
    process.exit(1);
});
